// client/src/pages/trust.tsx — Plain-language security/trust page
// Priority 2d: "How we protect your child's data" — written for a worried parent, not a lawyer.
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";

export default function Trust() {
  return (
    <>
      <Helmet>
        <title>How We Protect Your Child's Data — ScholarGuide</title>
        <meta name="description" content="Plain-language explanation of how ScholarGuide protects your child's data: what's collected, what's never sold, how to delete everything, COPPA/FERPA posture." />
      </Helmet>

      <div className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold mb-6">How We Protect Your Child's Data</h1>
        <p className="text-gray-600 mb-8">
          We know you're trusting us with information about your child. This page explains what we do with that
          information in plain language — not legal jargon. For the full legal text, see our Privacy Policy.
        </p>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">What we collect</h2>
          <ul className="space-y-2 text-gray-700">
            <li>• Your email and password (encrypted) for account access.</li>
            <li>• Your child's first name and grade level — that's it. We don't ask for last name, birthdate, school, or district.</li>
            <li>• Diagnostic results and practice session data — so we can show you growth over time.</li>
            <li>• Curriculum plans generated by AI based on your child's grade and diagnostic results.</li>
            <li>• Billing information is handled by Stripe — we never see or store your credit card number.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">What we never do</h2>
          <ul className="space-y-2 text-gray-700">
            <li>• <strong>We never sell your data.</strong> Not to anyone, ever.</li>
            <li>• <strong>We never share your child's data</strong> with advertisers, data brokers, or third parties.</li>
            <li>• <strong>We never use your child's data to train AI models.</strong> The AI that generates curriculum and lesson plans doesn't learn from your child's specific data.</li>
            <li>• <strong>We never post anything publicly</strong> about your child. The only way growth data leaves the app is if you explicitly download a shareable image — and even that uses first name only.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">How to delete everything</h2>
          <p className="text-gray-700 mb-3">
            You can delete your entire account — including all students, diagnostics, curriculum plans, and practice
            sessions — at any time. No questions, no retention period, no "soft delete." It's gone.
          </p>
          <p className="text-gray-700 mb-3">
            Go to <Link to="/settings" className="text-indigo-600 underline">Settings → Account → Delete my account</Link>.
            You'll see a confirmation dialog. Once confirmed, all your data is permanently deleted from our database
            within seconds.
          </p>
          <p className="text-gray-700">
            You can also <Link to="/settings" className="text-indigo-600 underline">export all your data</Link> as a JSON
            file before deleting, if you want to keep a copy.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">COPPA & FERPA</h2>
          <p className="text-gray-700 mb-3">
            <strong>COPPA</strong> (Children's Online Privacy Protection Act): ScholarGuide is designed for parents and
            educators to use on behalf of children. We don't collect personal information directly from children under 13.
            The parent or educator creates the account, and we only store the child's first name and grade level —
            not a full profile that would identify them.
          </p>
          <p className="text-gray-700">
            <strong>FERPA</strong> (Family Educational Rights and Privacy Act): ScholarGuide is not a school and doesn't
            receive educational records from schools. If you're an educator using ScholarGuide, you're responsible for
            complying with your institution's FERPA policies. We don't maintain educational records in the FERPA sense.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">Data security</h2>
          <ul className="space-y-2 text-gray-700">
            <li>• Passwords are hashed with bcrypt — we can't see your password even if we wanted to.</li>
            <li>• All traffic is encrypted with HTTPS.</li>
            <li>• Security headers (Helmet) protect against common web vulnerabilities.</li>
            <li>• Rate limiting prevents brute-force attacks on login.</li>
            <li>• The database is access-controlled and not publicly queryable.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">Questions?</h2>
          <p className="text-gray-700">
            If you have any questions about how we handle data, email us at
            <a href="mailto:hello@scholarguide.app" className="text-indigo-600 underline"> hello@scholarguide.app</a>.
            We'll respond within 48 hours.
          </p>
        </section>

        <div className="bg-indigo-50 border border-indigo-200 p-6 rounded-lg text-center">
          <p className="text-gray-700 mb-3">Ready to see your child's growth?</p>
          <Link to="/quick-check" className="inline-block bg-indigo-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-indigo-700">
            Try the Free Reading Check
          </Link>
        </div>
      </div>
    </>
  );
}
